import type { Technology, TechCategory } from "./types";

export const TECHNOLOGIES: Technology[] = [
  // ============================================================
  // STANDALONE LANGUAGES (for scripts, CLI, simple programs)
  // ============================================================
  {
    id: "python-lang",
    name: "Python",
    category: "language",
    attributes: {
      performanceAtScale: 5,
      learningCurve: 10,
      ecosystemMaturity: 10,
      timeToMVP: 10,
      costEfficiency: 10,
      typeSafety: 4,
      communitySize: 10,
      hiringEase: 10,
    },
    tags: ["scripting", "general-purpose", "ml", "data", "automation", "beginner-friendly"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["python"],
    platforms: ["script", "cli", "web", "desktop"],
  },
  {
    id: "rust-lang",
    name: "Rust",
    category: "language",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 2,
      ecosystemMaturity: 6,
      timeToMVP: 3,
      costEfficiency: 10,
      typeSafety: 10,
      communitySize: 6,
      hiringEase: 3,
    },
    tags: ["systems", "performance", "memory-safe", "concurrent", "wasm", "cli"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["rust"],
    platforms: ["cli", "desktop", "web", "mobile-android", "mobile-ios"],
  },
  {
    id: "go-lang",
    name: "Go",
    category: "language",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 7,
      ecosystemMaturity: 8,
      timeToMVP: 7,
      costEfficiency: 9,
      typeSafety: 8,
      communitySize: 8,
      hiringEase: 6,
    },
    tags: ["systems", "concurrent", "simple", "fast-compile", "cli", "cloud-native"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["go"],
    platforms: ["cli", "web"],
  },
  {
    id: "java-lang",
    name: "Java",
    category: "language",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 4,
      ecosystemMaturity: 10,
      timeToMVP: 4,
      costEfficiency: 6,
      typeSafety: 9,
      communitySize: 10,
      hiringEase: 9,
    },
    tags: ["enterprise", "jvm", "cross-platform", "robust", "android"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["java"],
    platforms: ["cli", "web", "desktop", "mobile-android"],
  },
  {
    id: "csharp-lang",
    name: "C#",
    category: "language",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 5,
      ecosystemMaturity: 9,
      timeToMVP: 6,
      costEfficiency: 7,
      typeSafety: 9,
      communitySize: 8,
      hiringEase: 7,
    },
    tags: ["dotnet", "enterprise", "cross-platform", "unity", "desktop"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["csharp"],
    platforms: ["cli", "web", "desktop", "mobile-cross"],
  },
  {
    id: "typescript-lang",
    name: "TypeScript / Node.js",
    category: "language",
    attributes: {
      performanceAtScale: 6,
      learningCurve: 7,
      ecosystemMaturity: 9,
      timeToMVP: 9,
      costEfficiency: 9,
      typeSafety: 8,
      communitySize: 10,
      hiringEase: 9,
    },
    tags: ["scripting", "fullstack", "npm", "versatile"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["script", "cli", "web"],
  },
  {
    id: "cpp-lang",
    name: "C++",
    category: "language",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 1,
      ecosystemMaturity: 10,
      timeToMVP: 2,
      costEfficiency: 10,
      typeSafety: 6,
      communitySize: 8,
      hiringEase: 5,
    },
    tags: ["systems", "performance", "embedded", "games", "low-level"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["cpp"],
    platforms: ["cli", "desktop", "mobile-android", "mobile-ios"],
  },
  {
    id: "c-lang",
    name: "C",
    category: "language",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 2,
      ecosystemMaturity: 10,
      timeToMVP: 2,
      costEfficiency: 10,
      typeSafety: 3,
      communitySize: 9,
      hiringEase: 5,
    },
    tags: ["systems", "embedded", "kernel", "low-level", "portable", "performance"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["c"],
    platforms: ["cli", "desktop", "mobile-android", "mobile-ios"],
  },
  {
    id: "lua-lang",
    name: "Lua",
    category: "language",
    attributes: {
      performanceAtScale: 6,
      learningCurve: 9,
      ecosystemMaturity: 7,
      timeToMVP: 8,
      costEfficiency: 10,
      typeSafety: 2,
      communitySize: 5,
      hiringEase: 3,
    },
    tags: ["scripting", "games", "embedded", "lightweight", "love2d", "roblox"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["lua"],
    platforms: ["script", "desktop"],
  },
  {
    id: "php-lang",
    name: "PHP",
    category: "language",
    attributes: {
      performanceAtScale: 6,
      learningCurve: 8,
      ecosystemMaturity: 10,
      timeToMVP: 9,
      costEfficiency: 10,
      typeSafety: 5,
      communitySize: 9,
      hiringEase: 8,
    },
    tags: ["web", "scripting", "wordpress", "laravel", "server-side"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["php"],
    platforms: ["web", "cli", "script"],
  },
  {
    id: "elixir-lang",
    name: "Elixir",
    category: "language",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 4,
      ecosystemMaturity: 6,
      timeToMVP: 6,
      costEfficiency: 9,
      typeSafety: 6,
      communitySize: 4,
      hiringEase: 2,
    },
    tags: ["functional", "concurrent", "fault-tolerant", "beam", "realtime", "phoenix"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["elixir"],
    platforms: ["web", "cli"],
  },
  {
    id: "ruby-lang",
    name: "Ruby",
    category: "language",
    attributes: {
      performanceAtScale: 5,
      learningCurve: 9,
      ecosystemMaturity: 9,
      timeToMVP: 10,
      costEfficiency: 8,
      typeSafety: 3,
      communitySize: 7,
      hiringEase: 5,
    },
    tags: ["scripting", "web", "rails", "elegant", "developer-happiness"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["ruby"],
    platforms: ["web", "cli", "script"],
  },
  {
    id: "dart-lang",
    name: "Dart",
    category: "language",
    attributes: {
      performanceAtScale: 7,
      learningCurve: 7,
      ecosystemMaturity: 6,
      timeToMVP: 8,
      costEfficiency: 9,
      typeSafety: 8,
      communitySize: 6,
      hiringEase: 4,
    },
    tags: ["flutter", "mobile", "cross-platform", "modern", "google"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["dart"],
    platforms: ["mobile-android", "mobile-ios", "mobile-cross", "web", "desktop"],
  },
  {
    id: "swift-lang",
    name: "Swift",
    category: "language",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 6,
      ecosystemMaturity: 8,
      timeToMVP: 7,
      costEfficiency: 8,
      typeSafety: 9,
      communitySize: 7,
      hiringEase: 5,
    },
    tags: ["apple", "ios", "macos", "native", "modern"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["swift"],
    platforms: ["mobile-ios", "desktop", "cli"],
  },
  {
    id: "kotlin-lang",
    name: "Kotlin",
    category: "language",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 6,
      ecosystemMaturity: 7,
      timeToMVP: 7,
      costEfficiency: 8,
      typeSafety: 9,
      communitySize: 7,
      hiringEase: 5,
    },
    tags: ["jvm", "android", "multiplatform", "modern", "concise"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["kotlin"],
    platforms: ["mobile-android", "mobile-cross", "cli", "web"],
  },

  // ============================================================
  // MOBILE FRAMEWORKS
  // ============================================================
  {
    id: "swift-ui",
    name: "SwiftUI",
    category: "mobile",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 6,
      ecosystemMaturity: 7,
      timeToMVP: 7,
      costEfficiency: 8,
      typeSafety: 9,
      communitySize: 7,
      hiringEase: 5,
    },
    tags: ["ios", "native", "declarative", "apple", "swiftui"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["swift"],
    platforms: ["mobile-ios"],
  },
  {
    id: "uikit",
    name: "UIKit",
    category: "mobile",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 4,
      ecosystemMaturity: 10,
      timeToMVP: 5,
      costEfficiency: 8,
      typeSafety: 8,
      communitySize: 8,
      hiringEase: 6,
    },
    tags: ["ios", "native", "imperative", "apple", "mature"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["swift"],
    platforms: ["mobile-ios"],
  },
  {
    id: "jetpack-compose",
    name: "Jetpack Compose",
    category: "mobile",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 6,
      ecosystemMaturity: 7,
      timeToMVP: 7,
      costEfficiency: 9,
      typeSafety: 9,
      communitySize: 7,
      hiringEase: 5,
    },
    tags: ["android", "native", "declarative", "google", "modern"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["kotlin"],
    platforms: ["mobile-android"],
  },
  {
    id: "react-native",
    name: "React Native",
    category: "mobile",
    attributes: {
      performanceAtScale: 6,
      learningCurve: 7,
      ecosystemMaturity: 8,
      timeToMVP: 9,
      costEfficiency: 9,
      typeSafety: 7,
      communitySize: 9,
      hiringEase: 8,
    },
    tags: ["cross-platform", "react", "javascript", "expo", "hybrid"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["mobile-ios", "mobile-android", "mobile-cross"],
  },
  {
    id: "flutter",
    name: "Flutter",
    category: "mobile",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 5,
      ecosystemMaturity: 7,
      timeToMVP: 8,
      costEfficiency: 9,
      typeSafety: 8,
      communitySize: 8,
      hiringEase: 5,
    },
    tags: ["cross-platform", "dart", "google", "widgets", "fast"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["dart"],
    platforms: ["mobile-ios", "mobile-android", "mobile-cross", "desktop"],
  },
  {
    id: "kotlin-multiplatform",
    name: "Kotlin Multiplatform",
    category: "mobile",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 4,
      ecosystemMaturity: 5,
      timeToMVP: 5,
      costEfficiency: 8,
      typeSafety: 9,
      communitySize: 5,
      hiringEase: 3,
    },
    tags: ["cross-platform", "native", "shared-logic", "jetbrains"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["kotlin"],
    platforms: ["mobile-ios", "mobile-android", "mobile-cross"],
  },
  {
    id: "expo",
    name: "Expo",
    category: "mobile",
    attributes: {
      performanceAtScale: 5,
      learningCurve: 9,
      ecosystemMaturity: 7,
      timeToMVP: 10,
      costEfficiency: 9,
      typeSafety: 7,
      communitySize: 8,
      hiringEase: 7,
    },
    tags: ["cross-platform", "react-native", "managed", "ota-updates", "easy"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["mobile-ios", "mobile-android", "mobile-cross"],
  },

  // ============================================================
  // DESKTOP FRAMEWORKS
  // ============================================================
  {
    id: "tauri",
    name: "Tauri",
    category: "desktop",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 5,
      ecosystemMaturity: 5,
      timeToMVP: 6,
      costEfficiency: 10,
      typeSafety: 9,
      communitySize: 5,
      hiringEase: 3,
    },
    tags: ["rust", "webview", "lightweight", "secure", "cross-platform", "small-binary"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["rust", "typescript", "javascript"],
    platforms: ["desktop", "mobile-ios", "mobile-android"],
  },
  {
    id: "electron",
    name: "Electron",
    category: "desktop",
    attributes: {
      performanceAtScale: 5,
      learningCurve: 8,
      ecosystemMaturity: 9,
      timeToMVP: 9,
      costEfficiency: 7,
      typeSafety: 7,
      communitySize: 9,
      hiringEase: 8,
    },
    tags: ["chromium", "nodejs", "cross-platform", "web-tech", "heavy"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["desktop"],
  },
  {
    id: "maui",
    name: ".NET MAUI",
    category: "desktop",
    attributes: {
      performanceAtScale: 7,
      learningCurve: 4,
      ecosystemMaturity: 6,
      timeToMVP: 5,
      costEfficiency: 8,
      typeSafety: 9,
      communitySize: 6,
      hiringEase: 5,
    },
    tags: ["dotnet", "cross-platform", "native", "microsoft", "xaml"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["csharp"],
    platforms: ["desktop", "mobile-ios", "mobile-android", "mobile-cross"],
  },
  {
    id: "qt",
    name: "Qt",
    category: "desktop",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 3,
      ecosystemMaturity: 10,
      timeToMVP: 4,
      costEfficiency: 7,
      typeSafety: 7,
      communitySize: 6,
      hiringEase: 4,
    },
    tags: ["cpp", "native", "cross-platform", "enterprise", "embedded"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["cpp", "python"],
    platforms: ["desktop"],
  },
  {
    id: "swiftui-macos",
    name: "SwiftUI (macOS)",
    category: "desktop",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 6,
      ecosystemMaturity: 7,
      timeToMVP: 7,
      costEfficiency: 9,
      typeSafety: 9,
      communitySize: 6,
      hiringEase: 4,
    },
    tags: ["apple", "native", "macos-only", "declarative"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["swift"],
    platforms: ["desktop"],
  },

  // ============================================================
  // BUILD TOOLS (for CLI/scripts)
  // ============================================================
  {
    id: "cargo",
    name: "Cargo",
    category: "build-tool",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 6,
      ecosystemMaturity: 8,
      timeToMVP: 6,
      costEfficiency: 10,
      typeSafety: 10,
      communitySize: 6,
      hiringEase: 3,
    },
    tags: ["rust", "package-manager", "build", "testing"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["rust"],
    platforms: ["cli", "desktop"],
  },
  {
    id: "clap",
    name: "Clap (Rust CLI)",
    category: "build-tool",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 6,
      ecosystemMaturity: 8,
      timeToMVP: 7,
      costEfficiency: 10,
      typeSafety: 10,
      communitySize: 6,
      hiringEase: 3,
    },
    tags: ["rust", "cli", "argument-parser", "derive"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["rust"],
    platforms: ["cli"],
  },
  {
    id: "cobra",
    name: "Cobra (Go CLI)",
    category: "build-tool",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 7,
      ecosystemMaturity: 9,
      timeToMVP: 8,
      costEfficiency: 10,
      typeSafety: 8,
      communitySize: 7,
      hiringEase: 5,
    },
    tags: ["go", "cli", "argument-parser", "kubectl", "docker"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["go"],
    platforms: ["cli"],
  },
  {
    id: "click",
    name: "Click (Python CLI)",
    category: "build-tool",
    attributes: {
      performanceAtScale: 5,
      learningCurve: 9,
      ecosystemMaturity: 9,
      timeToMVP: 10,
      costEfficiency: 10,
      typeSafety: 4,
      communitySize: 8,
      hiringEase: 8,
    },
    tags: ["python", "cli", "decorator", "simple"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["python"],
    platforms: ["cli"],
  },

  // ============================================================
  // FRONTEND FRAMEWORKS (web only)
  // ============================================================
  {
    id: "nextjs",
    name: "Next.js",
    category: "frontend",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 6,
      ecosystemMaturity: 9,
      timeToMVP: 9,
      costEfficiency: 9,
      typeSafety: 8,
      communitySize: 9,
      hiringEase: 8,
    },
    tags: ["ssr", "ssg", "react", "fullstack", "serverless", "api-routes", "seo", "edge"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  {
    id: "nuxt",
    name: "Nuxt",
    category: "frontend",
    attributes: {
      performanceAtScale: 7,
      learningCurve: 6,
      ecosystemMaturity: 7,
      timeToMVP: 8,
      costEfficiency: 8,
      typeSafety: 7,
      communitySize: 7,
      hiringEase: 6,
    },
    tags: ["ssr", "ssg", "vue", "fullstack", "seo"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  {
    id: "sveltekit",
    name: "SvelteKit",
    category: "frontend",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 8,
      ecosystemMaturity: 6,
      timeToMVP: 8,
      costEfficiency: 9,
      typeSafety: 7,
      communitySize: 5,
      hiringEase: 4,
    },
    tags: ["ssr", "ssg", "svelte", "fullstack", "seo", "lightweight"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  {
    id: "remix",
    name: "Remix",
    category: "frontend",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 5,
      ecosystemMaturity: 6,
      timeToMVP: 7,
      costEfficiency: 8,
      typeSafety: 8,
      communitySize: 5,
      hiringEase: 5,
    },
    tags: ["ssr", "react", "fullstack", "web-standards", "seo"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  {
    id: "astro",
    name: "Astro",
    category: "frontend",
    attributes: {
      performanceAtScale: 9,
      learningCurve: 8,
      ecosystemMaturity: 5,
      timeToMVP: 8,
      costEfficiency: 10,
      typeSafety: 7,
      communitySize: 5,
      hiringEase: 3,
    },
    tags: ["ssg", "content", "islands", "seo", "blog", "marketing", "lightweight"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  {
    id: "angular",
    name: "Angular",
    category: "frontend",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 3,
      ecosystemMaturity: 10,
      timeToMVP: 4,
      costEfficiency: 6,
      typeSafety: 10,
      communitySize: 8,
      hiringEase: 7,
    },
    tags: ["enterprise", "spa", "rxjs", "opinionated"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript"],
    platforms: ["web"],
  },
  // Standalone frameworks (without SSR meta-framework)
  {
    id: "vue",
    name: "Vue.js",
    category: "frontend",
    attributes: {
      performanceAtScale: 7,
      learningCurve: 8,
      ecosystemMaturity: 8,
      timeToMVP: 9,
      costEfficiency: 9,
      typeSafety: 7,
      communitySize: 8,
      hiringEase: 7,
    },
    tags: ["spa", "vue", "reactive", "progressive", "flexible"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  {
    id: "solid",
    name: "SolidJS",
    category: "frontend",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 5,
      ecosystemMaturity: 4,
      timeToMVP: 6,
      costEfficiency: 9,
      typeSafety: 8,
      communitySize: 3,
      hiringEase: 2,
    },
    tags: ["reactive", "fine-grained", "fast", "compiled", "no-vdom"],
    supportsRealtime: false,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["web"],
  },
  // Gaming / Creative / 3D frontend frameworks
  {
  // ========== GAME ENGINES ==========
    id: "threejs",
    name: "Three.js",
    category: "game",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 4,
      ecosystemMaturity: 9,
      timeToMVP: 5,
      costEfficiency: 10,
      typeSafety: 5,
      communitySize: 8,
      hiringEase: 4,
    },
    tags: ["3d", "webgl", "gaming", "animation", "visualization", "creative", "interactive"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["game", "web"],
  },
  {
    id: "phaser",
    name: "Phaser",
    category: "game",
    attributes: {
      performanceAtScale: 7,
      learningCurve: 7,
      ecosystemMaturity: 8,
      timeToMVP: 7,
      costEfficiency: 10,
      typeSafety: 5,
      communitySize: 6,
      hiringEase: 3,
    },
    tags: ["2d", "gaming", "game-engine", "canvas", "arcade", "pixel", "retro", "sprite"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["typescript", "javascript"],
    platforms: ["game", "web"],
  },
  {
    id: "p5js",
    name: "p5.js",
    category: "game",
    attributes: {
      performanceAtScale: 4,
      learningCurve: 10,
      ecosystemMaturity: 7,
      timeToMVP: 9,
      costEfficiency: 10,
      typeSafety: 3,
      communitySize: 6,
      hiringEase: 3,
    },
    tags: ["creative", "art", "generative", "canvas", "animation", "interactive", "sketch", "visual"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["javascript"],
    platforms: ["game", "web"],
  },
  {
    id: "bevy",
    name: "Bevy",
    category: "game",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 3,
      ecosystemMaturity: 3,
      timeToMVP: 4,
      costEfficiency: 10,
      typeSafety: 10,
      communitySize: 4,
      hiringEase: 1,
    },
    tags: ["game-engine", "ecs", "3d", "2d", "rust", "wasm", "gaming", "animation"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["rust"],
    platforms: ["game", "desktop", "web"],
  },
  {
    id: "pygame",
    name: "Pygame",
    category: "game",
    attributes: {
      performanceAtScale: 4,
      learningCurve: 9,
      ecosystemMaturity: 8,
      timeToMVP: 8,
      costEfficiency: 10,
      typeSafety: 3,
      communitySize: 7,
      hiringEase: 6,
    },
    tags: ["game-engine", "2d", "python", "gaming", "beginner", "arcade", "retro"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["python"],
    platforms: ["game", "desktop", "script"],
  },
  {
    id: "love2d",
    name: "LÖVE (Love2D)",
    category: "game",
    attributes: {
      performanceAtScale: 6,
      learningCurve: 9,
      ecosystemMaturity: 7,
      timeToMVP: 8,
      costEfficiency: 10,
      typeSafety: 2,
      communitySize: 4,
      hiringEase: 2,
    },
    tags: ["game-engine", "2d", "lua", "gaming", "lightweight", "indie", "pixel"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["lua"],
    platforms: ["game", "desktop"],
  },
  {
    id: "godot",
    name: "Godot",
    category: "game",
    attributes: {
      performanceAtScale: 7,
      learningCurve: 7,
      ecosystemMaturity: 6,
      timeToMVP: 7,
      costEfficiency: 10,
      typeSafety: 5,
      communitySize: 6,
      hiringEase: 3,
    },
    tags: ["game-engine", "2d", "3d", "gdscript", "gaming", "open-source", "indie"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["cpp", "c"],
    platforms: ["game", "desktop", "mobile-android", "mobile-ios", "web"],
  },
  {
    id: "unity",
    name: "Unity",
    category: "game",
    attributes: {
      performanceAtScale: 8,
      learningCurve: 5,
      ecosystemMaturity: 10,
      timeToMVP: 7,
      costEfficiency: 6,
      typeSafety: 8,
      communitySize: 10,
      hiringEase: 8,
    },
    tags: ["game-engine", "2d", "3d", "c-sharp", "gaming", "cross-platform", "ar", "vr"],
    supportsRealtime: true,
    freeHostingAvailable: false,
    languages: ["csharp"],
    platforms: ["game", "desktop", "mobile-android", "mobile-ios", "web"],
  },
  {
    id: "unreal",
    name: "Unreal Engine",
    category: "game",
    attributes: {
      performanceAtScale: 10,
      learningCurve: 2,
      ecosystemMaturity: 10,
      timeToMVP: 3,
      costEfficiency: 5,
      typeSafety: 8,
      communitySize: 9,
      hiringEase: 6,
    },
    tags: ["game-engine", "3d", "cpp", "gaming", "aaa", "cross-platform", "blueprint", "vr"],
    supportsRealtime: true,
    freeHostingAvailable: false,
    languages: ["cpp"],
    platforms: ["game", "desktop", "mobile-android", "mobile-ios"],
  },
  {
    id: "kaboom",
    name: "Kaboom.js",
    category: "game",
    attributes: {
      performanceAtScale: 5,
      learningCurve: 10,
      ecosystemMaturity: 4,
      timeToMVP: 10,
      costEfficiency: 10,
      typeSafety: 4,
      communitySize: 3,
      hiringEase: 2,
    },
    tags: ["game-engine", "2d", "gaming", "beginner", "arcade", "pixel", "browser"],
    supportsRealtime: true,
    freeHostingAvailable: true,
    languages: ["javascript"],
    platforms: ["game", "web"],
  },

  // ============================================================
  // BACKEND FRAMEWORKS (web + API)
  // ============================================================
  {
    id: "express",
    name: "Express.js",
    category: "backend",
    attributes: { performanceAtScale: 6, learningCurve: 9, ecosystemMaturity: 10, timeToMVP: 9, costEfficiency: 8, typeSafety: 5, communitySize: 10, hiringEase: 9 },
    tags: ["nodejs", "middleware", "api", "minimal", "flexible"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "fastify",
    name: "Fastify",
    category: "backend",
    attributes: { performanceAtScale: 9, learningCurve: 7, ecosystemMaturity: 7, timeToMVP: 8, costEfficiency: 8, typeSafety: 7, communitySize: 6, hiringEase: 5 },
    tags: ["nodejs", "api", "fast", "schema-validation", "plugins"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "django",
    name: "Django",
    category: "backend",
    attributes: { performanceAtScale: 7, learningCurve: 6, ecosystemMaturity: 10, timeToMVP: 8, costEfficiency: 7, typeSafety: 5, communitySize: 9, hiringEase: 7 },
    tags: ["python", "batteries-included", "admin", "orm", "auth", "cms"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["python"], platforms: ["web"],
  },
  {
    id: "rails",
    name: "Ruby on Rails",
    category: "backend",
    attributes: { performanceAtScale: 5, learningCurve: 6, ecosystemMaturity: 10, timeToMVP: 10, costEfficiency: 6, typeSafety: 3, communitySize: 7, hiringEase: 5 },
    tags: ["ruby", "mvc", "convention-over-config", "rapid", "monolith"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["ruby"], platforms: ["web"],
  },
  {
    id: "spring-boot",
    name: "Spring Boot",
    category: "backend",
    attributes: { performanceAtScale: 10, learningCurve: 3, ecosystemMaturity: 10, timeToMVP: 4, costEfficiency: 4, typeSafety: 10, communitySize: 9, hiringEase: 8 },
    tags: ["java", "enterprise", "microservices", "robust", "security"],
    supportsRealtime: true, freeHostingAvailable: false,
    languages: ["java", "kotlin"], platforms: ["web"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    category: "backend",
    attributes: { performanceAtScale: 8, learningCurve: 8, ecosystemMaturity: 6, timeToMVP: 9, costEfficiency: 8, typeSafety: 8, communitySize: 7, hiringEase: 6 },
    tags: ["python", "async", "api", "openapi", "pydantic", "ml"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["python"], platforms: ["web"],
  },
  {
    id: "go-fiber",
    name: "Go Fiber",
    category: "backend",
    attributes: { performanceAtScale: 10, learningCurve: 5, ecosystemMaturity: 5, timeToMVP: 5, costEfficiency: 9, typeSafety: 9, communitySize: 5, hiringEase: 4 },
    tags: ["go", "fast", "low-memory", "concurrent", "microservices"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["go"], platforms: ["web"],
  },
  {
    id: "actix",
    name: "Actix Web",
    category: "backend",
    attributes: { performanceAtScale: 10, learningCurve: 3, ecosystemMaturity: 5, timeToMVP: 4, costEfficiency: 10, typeSafety: 10, communitySize: 4, hiringEase: 2 },
    tags: ["rust", "fast", "concurrent", "async", "performance"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["rust"], platforms: ["web"],
  },
  {
    id: "convex",
    name: "Convex",
    category: "backend",
    attributes: { performanceAtScale: 7, learningCurve: 8, ecosystemMaturity: 4, timeToMVP: 10, costEfficiency: 7, typeSafety: 9, communitySize: 4, hiringEase: 3 },
    tags: ["baas", "realtime", "serverless", "typescript", "reactive", "schema"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "hono",
    name: "Hono",
    category: "backend",
    attributes: { performanceAtScale: 9, learningCurve: 8, ecosystemMaturity: 4, timeToMVP: 9, costEfficiency: 10, typeSafety: 8, communitySize: 4, hiringEase: 3 },
    tags: ["edge", "lightweight", "fast", "cloudflare", "bun", "deno", "serverless"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "nestjs",
    name: "NestJS",
    category: "backend",
    attributes: { performanceAtScale: 8, learningCurve: 4, ecosystemMaturity: 7, timeToMVP: 6, costEfficiency: 7, typeSafety: 9, communitySize: 7, hiringEase: 6 },
    tags: ["enterprise", "decorators", "modular", "graphql", "microservice", "opinionated"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["typescript"], platforms: ["web"],
  },
  {
    id: "gin",
    name: "Gin",
    category: "backend",
    attributes: { performanceAtScale: 9, learningCurve: 7, ecosystemMaturity: 8, timeToMVP: 7, costEfficiency: 10, typeSafety: 8, communitySize: 7, hiringEase: 5 },
    tags: ["go", "fast", "minimal", "rest", "middleware"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["go"], platforms: ["web"],
  },
  {
    id: "phoenix",
    name: "Phoenix",
    category: "backend",
    attributes: { performanceAtScale: 9, learningCurve: 4, ecosystemMaturity: 6, timeToMVP: 7, costEfficiency: 9, typeSafety: 6, communitySize: 4, hiringEase: 2 },
    tags: ["elixir", "realtime", "liveview", "channels", "fault-tolerant", "concurrent"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["elixir"], platforms: ["web"],
  },
  {
    id: "laravel",
    name: "Laravel",
    category: "backend",
    attributes: { performanceAtScale: 6, learningCurve: 7, ecosystemMaturity: 9, timeToMVP: 9, costEfficiency: 8, typeSafety: 5, communitySize: 9, hiringEase: 7 },
    tags: ["php", "fullstack", "eloquent", "blade", "batteries-included", "rapid"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["php"], platforms: ["web"],
  },
  {
    id: "flask",
    name: "Flask",
    category: "backend",
    attributes: { performanceAtScale: 5, learningCurve: 9, ecosystemMaturity: 9, timeToMVP: 9, costEfficiency: 9, typeSafety: 4, communitySize: 8, hiringEase: 7 },
    tags: ["python", "micro", "lightweight", "flexible", "jinja"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["python"], platforms: ["web"],
  },

  // ============================================================
  // DATABASES
  // ============================================================
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "database",
    attributes: { performanceAtScale: 9, learningCurve: 5, ecosystemMaturity: 10, timeToMVP: 6, costEfficiency: 9, typeSafety: 8, communitySize: 10, hiringEase: 9 },
    tags: ["sql", "relational", "acid", "jsonb", "full-text-search", "enterprise"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web", "desktop", "cli"],
  },
  {
    id: "mysql",
    name: "MySQL",
    category: "database",
    attributes: { performanceAtScale: 8, learningCurve: 7, ecosystemMaturity: 10, timeToMVP: 7, costEfficiency: 9, typeSafety: 7, communitySize: 10, hiringEase: 9 },
    tags: ["sql", "relational", "acid", "simple", "widely-used"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web", "desktop", "cli"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "database",
    attributes: { performanceAtScale: 7, learningCurve: 8, ecosystemMaturity: 8, timeToMVP: 9, costEfficiency: 6, typeSafety: 4, communitySize: 8, hiringEase: 7 },
    tags: ["nosql", "document", "flexible-schema", "json", "atlas"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web", "mobile-cross", "mobile-ios", "mobile-android"],
  },
  {
    id: "sqlite",
    name: "SQLite",
    category: "database",
    attributes: { performanceAtScale: 3, learningCurve: 10, ecosystemMaturity: 10, timeToMVP: 10, costEfficiency: 10, typeSafety: 6, communitySize: 8, hiringEase: 8 },
    tags: ["sql", "embedded", "zero-config", "lightweight", "file-based"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web", "desktop", "cli", "mobile-ios", "mobile-android", "mobile-cross"],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "database",
    attributes: { performanceAtScale: 7, learningCurve: 9, ecosystemMaturity: 5, timeToMVP: 10, costEfficiency: 8, typeSafety: 7, communitySize: 7, hiringEase: 5 },
    tags: ["sql", "baas", "realtime", "auth", "storage", "postgresql", "serverless"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web", "mobile-cross"],
  },
  {
    id: "dynamodb",
    name: "DynamoDB",
    category: "database",
    attributes: { performanceAtScale: 10, learningCurve: 4, ecosystemMaturity: 8, timeToMVP: 5, costEfficiency: 5, typeSafety: 5, communitySize: 6, hiringEase: 5 },
    tags: ["nosql", "aws", "serverless", "key-value", "enterprise", "managed"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "realm",
    name: "Realm",
    category: "database",
    attributes: { performanceAtScale: 7, learningCurve: 7, ecosystemMaturity: 7, timeToMVP: 8, costEfficiency: 8, typeSafety: 7, communitySize: 5, hiringEase: 4 },
    tags: ["mobile", "embedded", "offline-first", "sync", "mongodb"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["swift", "kotlin", "java"], platforms: ["mobile-ios", "mobile-android", "mobile-cross"],
  },
  {
    id: "core-data",
    name: "Core Data",
    category: "database",
    attributes: { performanceAtScale: 7, learningCurve: 3, ecosystemMaturity: 10, timeToMVP: 5, costEfficiency: 10, typeSafety: 7, communitySize: 6, hiringEase: 4 },
    tags: ["apple", "ios", "persistence", "native", "offline"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["swift"], platforms: ["mobile-ios"],
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "database",
    attributes: { performanceAtScale: 9, learningCurve: 7, ecosystemMaturity: 5, timeToMVP: 8, costEfficiency: 6, typeSafety: 7, communitySize: 4, hiringEase: 5 },
    tags: ["mysql", "sql", "serverless", "branching", "vitess", "scale"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "turso",
    name: "Turso",
    category: "database",
    attributes: { performanceAtScale: 8, learningCurve: 7, ecosystemMaturity: 3, timeToMVP: 8, costEfficiency: 9, typeSafety: 6, communitySize: 3, hiringEase: 3 },
    tags: ["sqlite", "sql", "edge", "embedded", "lightweight", "libsql"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web", "cli", "desktop"],
  },
  {
    id: "firestore",
    name: "Firestore",
    category: "database",
    attributes: { performanceAtScale: 7, learningCurve: 8, ecosystemMaturity: 8, timeToMVP: 9, costEfficiency: 5, typeSafety: 5, communitySize: 8, hiringEase: 6 },
    tags: ["nosql", "baas", "realtime", "firebase", "google", "mobile"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web", "mobile-android", "mobile-ios", "mobile-cross"],
  },

  // ============================================================
  // CACHE
  // ============================================================
  {
    id: "redis",
    name: "Redis",
    category: "cache",
    attributes: { performanceAtScale: 10, learningCurve: 7, ecosystemMaturity: 10, timeToMVP: 7, costEfficiency: 7, typeSafety: 3, communitySize: 9, hiringEase: 7 },
    tags: ["cache", "pubsub", "queue", "session", "realtime", "fast"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },

  // ============================================================
  // ORMs
  // ============================================================
  {
    id: "prisma",
    name: "Prisma",
    category: "orm",
    attributes: { performanceAtScale: 7, learningCurve: 8, ecosystemMaturity: 7, timeToMVP: 9, costEfficiency: 10, typeSafety: 10, communitySize: 8, hiringEase: 6 },
    tags: ["typescript", "schema", "migrations", "auto-generated", "sql"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "drizzle",
    name: "Drizzle",
    category: "orm",
    attributes: { performanceAtScale: 9, learningCurve: 6, ecosystemMaturity: 4, timeToMVP: 7, costEfficiency: 10, typeSafety: 10, communitySize: 5, hiringEase: 3 },
    tags: ["typescript", "sql-like", "lightweight", "edge", "serverless"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "sqlalchemy",
    name: "SQLAlchemy",
    category: "orm",
    attributes: { performanceAtScale: 8, learningCurve: 5, ecosystemMaturity: 10, timeToMVP: 6, costEfficiency: 10, typeSafety: 6, communitySize: 8, hiringEase: 6 },
    tags: ["python", "sql", "flexible", "enterprise"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["python"], platforms: ["web"],
  },
  {
    id: "activerecord",
    name: "Active Record",
    category: "orm",
    attributes: { performanceAtScale: 5, learningCurve: 8, ecosystemMaturity: 10, timeToMVP: 10, costEfficiency: 10, typeSafety: 3, communitySize: 7, hiringEase: 5 },
    tags: ["ruby", "convention", "migrations", "rails"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["ruby"], platforms: ["web"],
  },

  // ============================================================
  // HOSTING
  // ============================================================
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    attributes: { performanceAtScale: 8, learningCurve: 10, ecosystemMaturity: 8, timeToMVP: 10, costEfficiency: 7, typeSafety: 5, communitySize: 8, hiringEase: 5 },
    tags: ["serverless", "edge", "nextjs", "preview", "ci-cd", "managed"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "aws",
    name: "AWS",
    category: "hosting",
    attributes: { performanceAtScale: 10, learningCurve: 2, ecosystemMaturity: 10, timeToMVP: 3, costEfficiency: 5, typeSafety: 5, communitySize: 10, hiringEase: 9 },
    tags: ["enterprise", "serverless", "containers", "vps", "global", "managed"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "railway",
    name: "Railway",
    category: "hosting",
    attributes: { performanceAtScale: 6, learningCurve: 9, ecosystemMaturity: 5, timeToMVP: 9, costEfficiency: 7, typeSafety: 5, communitySize: 5, hiringEase: 3 },
    tags: ["managed", "containers", "simple", "postgres", "redis"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "flyio",
    name: "Fly.io",
    category: "hosting",
    attributes: { performanceAtScale: 8, learningCurve: 6, ecosystemMaturity: 6, timeToMVP: 7, costEfficiency: 8, typeSafety: 5, communitySize: 5, hiringEase: 3 },
    tags: ["containers", "edge", "global", "docker"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "hosting",
    attributes: { performanceAtScale: 7, learningCurve: 7, ecosystemMaturity: 8, timeToMVP: 6, costEfficiency: 8, typeSafety: 5, communitySize: 7, hiringEase: 5 },
    tags: ["vps", "containers", "managed", "droplets", "kubernetes"],
    supportsRealtime: true, freeHostingAvailable: false,
    languages: [], platforms: ["web"],
  },
  {
    id: "app-store",
    name: "Apple App Store",
    category: "hosting",
    attributes: { performanceAtScale: 10, learningCurve: 4, ecosystemMaturity: 10, timeToMVP: 3, costEfficiency: 4, typeSafety: 5, communitySize: 10, hiringEase: 5 },
    tags: ["ios", "distribution", "apple", "native"],
    supportsRealtime: false, freeHostingAvailable: false,
    languages: ["swift"], platforms: ["mobile-ios"],
  },
  {
    id: "play-store",
    name: "Google Play Store",
    category: "hosting",
    attributes: { performanceAtScale: 10, learningCurve: 5, ecosystemMaturity: 10, timeToMVP: 4, costEfficiency: 5, typeSafety: 5, communitySize: 10, hiringEase: 5 },
    tags: ["android", "distribution", "google", "native"],
    supportsRealtime: false, freeHostingAvailable: false,
    languages: ["kotlin", "java"], platforms: ["mobile-android"],
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "hosting",
    attributes: { performanceAtScale: 7, learningCurve: 9, ecosystemMaturity: 8, timeToMVP: 9, costEfficiency: 8, typeSafety: 5, communitySize: 7, hiringEase: 6 },
    tags: ["static", "jamstack", "serverless", "edge", "ci-cd", "forms"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "cloudflare-pages",
    name: "Cloudflare Pages",
    category: "hosting",
    attributes: { performanceAtScale: 9, learningCurve: 6, ecosystemMaturity: 6, timeToMVP: 7, costEfficiency: 9, typeSafety: 5, communitySize: 6, hiringEase: 5 },
    tags: ["edge", "workers", "serverless", "global", "fast", "d1", "r2"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },
  {
    id: "render",
    name: "Render",
    category: "hosting",
    attributes: { performanceAtScale: 7, learningCurve: 8, ecosystemMaturity: 5, timeToMVP: 8, costEfficiency: 7, typeSafety: 5, communitySize: 4, hiringEase: 4 },
    tags: ["containers", "docker", "heroku-alternative", "background-workers"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: [], platforms: ["web"],
  },

  // ============================================================
  // AUTH
  // ============================================================
  {
    id: "nextauth",
    name: "NextAuth.js",
    category: "auth",
    attributes: { performanceAtScale: 7, learningCurve: 7, ecosystemMaturity: 7, timeToMVP: 9, costEfficiency: 10, typeSafety: 7, communitySize: 7, hiringEase: 5 },
    tags: ["nextjs", "oauth", "jwt", "session", "providers"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    attributes: { performanceAtScale: 8, learningCurve: 9, ecosystemMaturity: 6, timeToMVP: 10, costEfficiency: 6, typeSafety: 8, communitySize: 5, hiringEase: 4 },
    tags: ["managed", "ui-components", "webhooks", "organizations"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    attributes: { performanceAtScale: 9, learningCurve: 5, ecosystemMaturity: 9, timeToMVP: 7, costEfficiency: 4, typeSafety: 6, communitySize: 8, hiringEase: 7 },
    tags: ["enterprise", "oauth", "saml", "sso", "managed", "multi-language"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web", "mobile-ios", "mobile-android"],
  },
  {
    id: "firebase-auth",
    name: "Firebase Auth",
    category: "auth",
    attributes: { performanceAtScale: 8, learningCurve: 9, ecosystemMaturity: 9, timeToMVP: 10, costEfficiency: 8, typeSafety: 5, communitySize: 9, hiringEase: 7 },
    tags: ["google", "mobile", "social-login", "anonymous", "phone"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: [], platforms: ["web", "mobile-ios", "mobile-android", "mobile-cross"],
  },

  // ============================================================
  // CMS
  // ============================================================
  {
    id: "sanity",
    name: "Sanity",
    category: "cms",
    attributes: { performanceAtScale: 8, learningCurve: 6, ecosystemMaturity: 7, timeToMVP: 8, costEfficiency: 7, typeSafety: 7, communitySize: 6, hiringEase: 4 },
    tags: ["headless", "structured-content", "realtime", "groq", "customizable"],
    supportsRealtime: true, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
  {
    id: "strapi",
    name: "Strapi",
    category: "cms",
    attributes: { performanceAtScale: 6, learningCurve: 8, ecosystemMaturity: 7, timeToMVP: 9, costEfficiency: 9, typeSafety: 5, communitySize: 7, hiringEase: 4 },
    tags: ["headless", "self-hosted", "admin-panel", "rest", "graphql"],
    supportsRealtime: false, freeHostingAvailable: true,
    languages: ["typescript", "javascript"], platforms: ["web"],
  },
];

export function getTechById(id: string): Technology | undefined {
  return TECHNOLOGIES.find((t) => t.id === id);
}

export function getTechsByCategory(category: TechCategory): Technology[] {
  return TECHNOLOGIES.filter((t) => t.category === category);
}
